### ISSUE TITLE
React example 

### ISSUE THREAD

**Issue by rizkyramadhan** [c-smile/sciter-js-sdk#1]
If you have react example with webpack / npm support, it will be easy sell to my team.

**Comment by JohnMcLear** [comment]
Isn't the point of this project to make something without all the cruft/baggage that react includes?

**Comment by rizkyramadhan** [comment]
Yeah... but we like react, and also the resulting output are  small static html js, I think it makes sense if this can be a wrapper like electron does - without it's bloat.

**Comment by c-smile** [comment]
You should be able to run React as it is, or at least with some (I hope thin) compatibility layer.

For that matter: in "big" Sciter I've added  native SSX (a.k.a. JSX) support and **native** reconciliation mechanism (a.k.a. Reactor). So React in Sciter is implemented natively - essentially Sciter has ReactJS built-in - available out of the box, see:  https://sciter.com/developers/sciter-docs/reactor-and-ssx/

I have similar plans for Sciter.JS.  JSX will be built-in into its JS natively, yet Element.patch(vdom) will also be available out of the box. So ReactJS will either run as it is (requires JSX preprocessor/Babel ?) or it will be more effective port of ReactJS - **native React** (not to be confused with React Native that is completely different thing).

**Comment by c-smile** [comment]
Just in case: I have [mithril](https://mithril.js.org) running as it is in Sciter.JS. Yet I've added native JSX support in script.

This is how canonical Mithril sample looks like in Sciter.JS: 

```
<html>
    <head>
        <title>Test</title>
        <style></style>
        <script src="../mithril.min.js" />
        <script>
          JSX = m;   // let's  use Mithril as a driver of JSX expressions
          var count = 0; // added a variable
          class Hello 
          {
            view() 
            {
              return <main>
                  <h1 class="title">My first JSX/mithril Sciter.JS app</h1>
                  <button onclick={ function(){count++} }>{count} clicks</button>
                </main>;
            }
          }
          m.mount(document.body, Hello);
        </script>
    </head>
    <body>
      <main>?</main>
    </body>
</html>
```
Runs out of the box - no preprocessing is required.

**Comment by rizkyramadhan** [comment]
> I have similar plans for Sciter.JS. JSX will be built-in into its JS natively, yet Element.patch(vdom) will also be available out of the box. So ReactJS will either run as it is (requires JSX preprocessor/Babel ?) or it will be more effective port of ReactJS - native React (not to be confused with React Native that is completely different thing).

I vote to use ReactJS as it is, because we have so many problem with react native, eventually we ditch it and go with pure reactjs with [capacitor](https://capacitorjs.com/) - I think this project will face same hurdle with react native when the same approach is taken.

IMO, The value of react is in it's ecosystem not it's reconciliation/vdom/engine thing...

**Comment by c-smile** [comment]
ReactJS should work as it is.  Or at least with some minimal compatibility layer.

As I said, this is not about "react native" but rather about native implementation of some functions used in ReactJS,
So we may have ReactJs port/patch optimized for Sciter and desktop in general.

**Comment by GirkovArpa** [comment]
> **native React** (not to be confused with React Native that is completely different thing).

> I vote to use ReactJS as it is, because we have so many problem with react native

🤦‍♂️@rizkyramadhan This issue is a joke, I hope it gets closed.  It's asking to support React, webpack, and NPM, then responding without even reading the replies from the maintainer.

**Comment by rizkyramadhan** [comment]
> > **native React** (not to be confused with React Native that is completely different thing).
> 
> > I vote to use ReactJS as it is, because we have so many problem with react native
> 
> 🤦‍♂️@rizkyramadhan This issue is a joke, I hope it gets closed. It's asking to support React, webpack, and NPM, then responding without even reading the replies from the maintainer.

Yeah, sorry...
