### ISSUE TITLE
How to react to doument close event for sicter js ?

### ISSUE THREAD

**Issue by toplinuxsir** [c-smile/sciter-js-sdk#102]
How to react to doument close event for sicter js ?
Thanks !

**Comment by MustafaHi** [comment]
`document.on('close', () => {   })`

event's for document are listed here,

https://github.com/c-smile/sciter-js-sdk/blob/main/docs/md/Event.md#document-lifecycle

in order which called first:

- "closerequest"

- "beforeunload"

- "close" | "unload"
