### ISSUE TITLE
How to pollyfill document.dispatchEvent?

### ISSUE THREAD

**Issue by 4silvertooth** [c-smile/sciter-js-sdk#11]
I am playing around converting a simple svelte project to sciter.js, svelte heavily depends on createEvent and dispatchEvent for reactivity. I am pollyfilling createEvent like this.

```
Element.prototype.createEvent = function(name) {
  const evt = new Event(name);
  return evt;
}

Event.prototype.initCustomEvent = function(type, canBubble, cancelable, detail){
  this.type = type;
  this.bubbles = canBubble;
  this.cancelable = cancelable;
  this.detail = detail;
  //return this;
}

```
but how do I pollyfill document.dispatchEvent?

**Comment by c-smile** [comment]
This should be made on my side.

I'll add `dispatchEvent` ASAP

**Comment by jsprog** [comment]
The default template of svelte (rollup) doesn't depends on 'dispatchEvent' and 'createEvent' for builds. But this change the moment you bring createEventDispatcher() to your code.

I tried to polyfill them days ago but the Event object wasn't available at that time. Even some native modules and documentation landed just recently, and this should help by bringing fixes to LiveReload.

Your question isn't stating anything about LiveReload, and I suppose that by applying the changes below, you should be able to run svelte's default template and even develop some code. 

```js
// rollup.config.js
plugins: [
    ...
    svelte({
        ...
        // dev: !production, // uncomment to generate code similar to build
       ...
    })

    // !production && livereload('public'), // uncomment to get rid of window

    // remove __proto__:null, from the generated bundle (only if your code use import * as all from './mod'
    replace({
        delimiters: ['', ''],
        "__proto__: null,": ""
    })
]
```

Notes:
If you really need to dispatch some non custom events to parent components, consider using something like <button {click}>Test Button</button> and it should work

**Comment by 4silvertooth** [comment]
> This should be made on my side.
> 
> I'll add `dispatchEvent` ASAP

I think txiki.js has that.

**Comment by 4silvertooth** [comment]
> The default template of svelte (rollup) doesn't depend on 'dispatchEvent' and 'createEvent' for builds. But this change the moment you bring createEventDispatcher() to your code.

Yes the default template works as it is, I was trying the button click counter, just like the mithril sample one.

[Svelte Counter](https://svelte.dev/repl/f5acc8113ec14bc7946eff9687916fa1?version=3.4.1)

**Comment by c-smile** [comment]
Document.dispatchEvent() landed into 4.4.5.5

**Comment by 4silvertooth** [comment]
I am able to run the Click Counter sample from svelte (without livereload) now, but with minor css glitches. 

![2020-11-13 11-48-43](https://user-images.githubusercontent.com/793967/99035951-b5cf6980-25a6-11eb-951b-5907afd31780.gif)

Also Svelte uses [Node.data](https://stackoverflow.com/questions/12286975/when-working-with-text-nodes-should-i-use-the-data-nodevalue-textcontent) so had to replace that with Node.nodeValue / Node.textContent in bundle.js directly.

**Comment by jsprog** [comment]
@4silvertooth good catch,
It's already available as `text.data = data;` at `svelte/internal/index.js` and I had to:
```js
replace({
	delimiters: ['', ''],
	"__proto__: null,": "",
	"text.data = data;": "text.nodeValue = data;",
}),
```

the word `text` in the code is for a textNode.

You can event dispatch to parents without dispatchEvent but the dev mode require it. and we can benefit by comparing both outputs from dev and production mode.

Some other links about dispatchEvent and a polyfill:
[https://javascript.info/dispatch-events](https://javascript.info/dispatch-events)
[https://gist.github.com/htmlpluscss/3b7183bde6f166d517f9015fe4b42873](https://gist.github.com/htmlpluscss/3b7183bde6f166d517f9015fe4b42873)

**Comment by jsprog** [comment]
For anyone trying to polyfill `initCustomEvent` using the code above. you may get this error (not sure if all platforms are affected):
> error:script: TypeError: no setter for property

Please, consider using this instead:
```js
Event.prototype.initCustomEvent = function (type, canBubble, cancelable, detail) {
	Object.defineProperty(this, 'type', { value: type })
	Object.defineProperty(this, 'bubbles', { value: canBubble } )
	Object.defineProperty(this, 'cancelable', { value: cancelable })
	Object.defineProperty(this, 'detail', { value: detail })
	return this;
}
```

**Comment by 4silvertooth** [comment]
Which platform are you testing that? In windows the above polyyfill works.

**Comment by jsprog** [comment]
> Which platform are you testing that? In windows the above polyfill works.

I'm testing on LMDE4 (x64)

> Also by the Specification
> it shouldn't return anything and should return if this's dispatch flag is set.

This was there in the code you shared, and thanks to it, I has just to copy and paste it and apply some changes.

The dev mode is working except for the live reload and we need to worry about script injection and WebSocket.

**Comment by c-smile** [comment]
I've added support for CustomEvent so this works:

```
el.dispatchEvent(new CustomEvent("file-drop", {detail:files, bubbles:true}));
```

[According to MDN initCustomEvent is deprecated](https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/initCustomEvent)
