### ISSUE TITLE
Can not connect to inspector.

### ISSUE THREAD

**Issue by kitepad** [c-smile/sciter-js-sdk#121]
**Describe the bug**

Clone latest repository and run inspector.exe, run scapp.exe with any demo. But can not connect to inspector.
Switch to old version, such as 4.4.5, 4.4.6, it's work.

**To Reproduce**
1. Clone latest repository
2. Run inspector.exe
3. Run scapp.exe with any sample
4. Can not connect to inspector.

**Expected behavior**
Inspector should show sample's dom. (CTRL+SHIFT+I shortcuts)

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MustafaHi** [comment]
It must launched with `--debug` argument

```cmd
> scapp --debug file.html
```

**Comment by kitepad** [comment]
Thanks. Where to find document about this?

**Comment by kitepad** [comment]
I launch my test html with --debug args, connect to inspector successfully, but I only see scapp about window without my app window shown. Why?

**Comment by kitepad** [comment]
It's ok if I launched my app like this: scapp scapp.htm --debug.
