### ISSUE TITLE
QuickJS modules are uninitialized.

### ISSUE THREAD

**Issue by NeoVance** [c-smile/sciter-js-sdk#123]
QuickJS exposes `std` and `os` modules to the JS. These appear to be uninitialized in Sciter.JS. This might not be a problem for the most part because the Sciter.JS API has some of the same functionality through `@sys`, except an important part of the original QuickJS API is missing. Namely the ability to load external script files and execute them in a different context, `eval` JS from within JS,  and execute JS scripts in a worker thread.

Reproduce:
Create a basic Sciter.JS native project using the template.
Create a JS module which will `import * as std from 'std'`
Add the JS module to your entry html page.
Build, and run the project.

`std` is an empty object.

**Comment by c-smile** [comment]
Please check this discussion: https://sciter.com/forums/topic/quickjs-std-module/
