### ISSUE TITLE
[Improvement] file-create.htm sample doesn't write user-inputted text to file

### ISSUE THREAD

**Issue by Prid13** [c-smile/sciter-js-sdk#132]
The sample located in the directory listed below forgets to take the user-inputted text value into account when writing to the file. Instead, the hardcoded value `"test"` is written to the file.

**Directory:** `samples.sciter/@sys/fs/file-create.htm`
**Line:** https://github.com/c-smile/sciter-js-sdk/blob/9f3a762fb5c83bed44ec06e5427b7524249150ab/samples.sciter/%40sys/fs/file-create.htm#L13

**Suggested improvement:**

```javascript
const text = document.$('#text').value;
await file.write(text);
```

**Comment by 8ctopus** [comment]
https://github.com/c-smile/sciter-js-sdk/pull/140 fixed it
