### ISSUE TITLE
Audio.resume() doesn't work

### ISSUE THREAD

**Issue by GirkovArpa** [c-smile/sciter-js-sdk#137]
**Describe the bug**
`Audio.resume()` does not resume the audio.

**To Reproduce**
Replace the JavaScript in `samples.sciter/audio` with this:

```javascript
document.on("click", "button#play", async function(evt,btn) {
  var audio = await Audio.load(__DIR__ + "/hasta-lavista-baby.mp3");
  audio.play();
  await new Promise((resolve) => setTimeout(resolve, 500));
  audio.pause();
  await new Promise((resolve) => setTimeout(resolve, 500));
  audio.resume();
});
```

**Expected behavior**
The audio should play for 500ms, pause for 500ms, then resume.  But it doesn't resume.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

I need this feature for [my MP3 player](https://github.com/GirkovArpa/lite-musik):

![https://github.com/GirkovArpa/lite-musik](https://github.com/GirkovArpa/lite-musik/raw/master/preview.gif)

**Comment by c-smile** [comment]
Yeah, thanks.

Fixed in r8811, will appear in the next build
