### ISSUE TITLE
Element.scrollTo does not send a scroll event

### ISSUE THREAD

**Issue by russo-2025** [c-smile/sciter-js-sdk#142]
**Describe the bug**
Element.scrollTo does not send a scroll event

**To Reproduce**
```
<html>
    <head>
        <style>
            #test {
                width: 100%;
                height: 100%;
                background-color: indianred;
                overflow: scroll;
            }
            #test div {
                width: 100%;
                height: 300%;
            }
        </style>
        <script type="module">
            let el = document.querySelector("#test")
            el.addEventListener("scroll", () => console.log("on scroll"))
            el.scrollTo(0, 150)
        </script>
    </head>
    <body>
        <div id="test"><div></div></div>
    </body>
</html>
```

**Expected behavior**
Sending the scroll event when calling the scrollTo method

**Screenshots**
![image](https://user-images.githubusercontent.com/28739948/126274577-9ab0b143-048f-4ed0-a346-72132a773442.png)

**Desktop (please complete the following information):**
 - OS: win 10
 - Browser Microsoft Edge 91.0.864.64
 - Version 4.4.8.4

**Additional context**

**Comment by c-smile** [comment]
That's tricky one.

Normally Sciter does not generate events that were initiated by code (native or script).
Only after user interactions.

On code side you simply can do 
```JS
el.scrollTo(0, 150);
el.onscroll();
```
Reason: to prevent potential "event loops".
