### ISSUE TITLE
the behavior of keyup/keydown events in the browser and sciter.js

### ISSUE THREAD

**Issue by russo-2025** [c-smile/sciter-js-sdk#148]
**Describe the bug**
the behavior of keyup/keydown events in the browser and sciter.js

**To Reproduce**
1.
```
<html>
    <head>
        <style>
			html, body {
				overflow: hidden;
			}
        </style>
        <script type="module">
            document.body.addEventListener("keydown", (e) => console.log("keydown"))
            document.body.addEventListener("keyup", (e) => console.log("keyup"))
        </script>
    </head>
    <body>
    </body>
</html>
```
2. Press any key

**Expected behavior**
Displaying keyup/keydown messages when pressed

**Screenshots**
![image](https://user-images.githubusercontent.com/28739948/126689675-06ceb0f8-114f-4dc4-8591-5e63d9e44c43.png)

**Desktop (please complete the following information):**
 - OS: win 10
 - Browser Microsoft Edge 91.0.864.64
 - Version 4.4.8.4

**Additional context**

**Comment by c-smile** [comment]
body element is not focusable by default in Sciter.

In order your code to work either make body focusable:

```html
<body tabindex="1">
```
or attach handlers to the document directly.
