### ISSUE TITLE
window-frame="transparent" no longer working on macOS w/ 4.4.8.6

### ISSUE THREAD

**Issue by AlecHaring** [c-smile/sciter-js-sdk#158]
Transparent window frames seem to be broken in the newest update

**To Reproduce**
- With the newest version of SciterJS, open the `window-chrome-types.htm` demo using scapp or uSciter
- Click the `window-frame="transparent"` button
- The areas that should be transparent are actually black

**Screenshots**
Sciter 4.4.8.6:
![Screen Shot 2021-08-09 at 5 34 28 PM](https://user-images.githubusercontent.com/19616756/128778111-11a2247b-7b84-4797-9f9f-05980f8305b3.png)
Older versions:
![Screen Shot 2021-08-09 at 5 37 51 PM](https://user-images.githubusercontent.com/19616756/128778141-59b44444-8168-4dfc-9add-e382b36b87b2.png)

**Desktop:**
OS: macOS Big Sur 11.4
Version: 4.4.8.6

**Comment by c-smile** [comment]
Fixed in 4.4.8.7
