### ISSUE TITLE
som bind won't compile

### ISSUE THREAD

**Issue by ttsping** [c-smile/sciter-js-sdk#163]
function with const or ref parameter won't compile.
sample code:
```
struct test_om_asset : sciter::om::asset<test_om_asset>
{
    SOM_PASSPORT_BEGIN(test_om_asset)
        SOM_FUNCS(SOM_FUNC(func))
    SOM_PASSPORT_END
    void func(const sciter::string& text);
}
```

vs output:
> 1>E:\xxx\sciter-js-sdk\include\value.hpp(375,1): error C2528: 'abstract declarator': pointer to reference is illegal
> 1>E:\xxx\sciter-js-sdk\include\sciter-om-def.h(240): message : see reference to function template instantiation 'T sciter::value::get<P2>(void) const' being compiled
> 1>        with
> 1>        [
> 1>            T=const sciter::string &,
> 1>            P2=const sciter::string &
> 1>        ]

**Comment by c-smile** [comment]
That's the limitation of the reflection implementation - only passing arguments by value is supported.

Arguments are fetched from sciter::value's, so, in case of string, there is no clear string variable to get reference of.

**Comment by ttsping** [comment]
removing qualifiers before call 'get' in the thunk function works. plz consider to fix it, in this case, get string from sciter::value, and pass it by const ref to function to avoid copy it.
```
template <class Type, class P0>
      struct member_function<void(Type::*)(P0)> {
        enum { n_params = 1 };
        template <void(Type::*Func)(P0)> static SBOOL thunk(som_asset_t* thing, UINT argc, const SOM_VALUE* argv, SOM_VALUE* p_result)
        {
          using RP0 = std::remove_const_t<std::remove_reference_t<P0>>;
          try { (static_cast<Type*>(thing)->*Func)(argv[0].get<RP0>()); *p_result = SOM_VALUE(); return TRUE; }
          catch (exception& e) { *p_result = SOM_VALUE::make_error(e.what()); return TRUE; }
        }
      };
```

**Comment by c-smile** [comment]
fixed by : https://github.com/c-smile/sciter-js-sdk/commit/d1bff00309ff102f5d21d1188d28dff51be96bd0

**Comment by ttsping** [comment]
thanks for the quick fix. 
there is another relate issue: the 'som_asset_t' type support,
sample code:
```
struct test_om_asset : sciter::om::asset<test_om_asset>
{
    SOM_PASSPORT_BEGIN(test_om_asset)
        SOM_FUNCS(SOM_FUNC(append))
    SOM_PASSPORT_END
    void append(test_om_asset* owner);
}
```
it should work if add getter like?
```
template<typename T, typename = std::enable_if_t<std::is_base_of_v<som_asset_t, T>>>
inline T* getter(const value& v, T**) { return v.get_asset<T>(); }
```
