### ISSUE TITLE
tiscript view equivalent

### ISSUE THREAD

**Issue by brihoumb** [c-smile/sciter-js-sdk#17]
Cannot find a way to call function from another language (pysciter) with window and I cannot find any tiscript view equivalent.

Will it be implemented later or is it already implemented ?

![image](https://user-images.githubusercontent.com/24702221/99160854-e9bca300-26fc-11eb-9673-f7cb8466f7d4.png)

**Comment by c-smile** [comment]
Sciter's `view`  is `Window.this`  in Sciter.JS.

`SciterEval` and  `SciterCall` APIs will work in next release.

**Comment by brihoumb** [comment]
Thank you very much!
