### ISSUE TITLE
Storage.open(...) fails with "Storage error: 2"

### ISSUE THREAD

**Issue by tuckerchapin** [c-smile/sciter-js-sdk#176]
**Describe the bug**
I'm trying to use the built-in storage system, but can't get off the ground as `Storage.open(...)` fails.

**To Reproduce**
```
$ scapp ./index.html # files below
> Storage error: 2 - 'Failed to create database file'
> null
> [object]
```

**Expected behavior**
The creation of a new database file and storage object.

**Desktop (please complete the following information):**
 - OS: Raspbian Buster
 - Version: /bin/linux/arm32/scapp @ main

**Additional context**
`index.html`:
```
<!DOCTYPE html>
<html>
<head>
  <script defer src="./main.js" type="module"></script>
</head>

<body>
</body>
</html>
```

`main.js`:
```
import * as Storage from '@storage';

let storage = Storage.open('~/Develop/sciter-playground/test.db');
```

**Comment by iakuf** [comment]
i have some problem

**Comment by c-smile** [comment]
Please try to put real path instead of `~/Develop/sciter-playground/test.db`

That '~' is purely a shell thing: https://stackoverflow.com/questions/57852502/open-an-ofstream-with-tilde-in-path-name
