### ISSUE TITLE
mdview and quark.js executables not working on Windows

### ISSUE THREAD

**Issue by 8ctopus** [c-smile/sciter-js-sdk#180]
The following executables are showing the scapp default window, most likely because the entrypoint `main.htm` was not set correctly during compilation.

sciter-js-sdk\bin\windows\x32\windows\x32\mdview.exe
sciter-js-sdk\bin\windows\x32\windows\x32\quark.js.exe

In addition, mdview is duplicated here:

sciter-js-sdk\bin\windows\x32\mdview.exe

**Comment by GirkovArpa** [comment]
Have you tried renaming the file `main.html` or `index.html` or `index.htm`?

**Comment by 8ctopus** [comment]
@GirkovArpa How would I do that inside the exe?

**Comment by GirkovArpa** [comment]
My bad, I misread your post as being about executables compiled by Quark.  But the problem is Quark itself (I just tried it and can confirm).

**Comment by 8ctopus** [comment]
Problem no longer exists in 4.4.8.15 because both exes were deleted.
