### ISSUE TITLE
Colorizer sample will "Not respond" when input ‘/*’  in windows

### ISSUE THREAD

**Issue by kitepad** [c-smile/sciter-js-sdk#183]
**Describe the bug**
Scapp.exe will not respond when you typed '/*' in script or style block, but it's ok in markup block.

**To Reproduce**
1. Go to 'samples.sciter\colorizer' folder 
2. run scapp test-editor.htm
3. insert '/*' in style block or javascript block
4. app is not respond.

**Desktop (please complete the following information):**
 - OS: Windows 11 or windows 10
 - Version 4.4.8.9

**Additional context**
You can input '/' or '*' firstly, but without space between them.

**Comment by c-smile** [comment]
Thanks, fixed here already.

**Comment by kitepad** [comment]
Thanks. I will try it when it's ready on git.

**Comment by kitepad** [comment]
I don't find any update about this fix. Will Next release includes fix?
