### ISSUE TITLE
contentEditable not working

### ISSUE THREAD

**Issue by saasira** [c-smile/sciter-js-sdk#190]
Hi,

It seems contentEditable feature  is not implemented yet by Sciter Engine; may we know if it will be implement at a later time, or or not in the scope at all?

Thanks,
Samba

**Comment by c-smile** [comment]
Sciter does not support contenteditable as it is quite limited feature. 

Instead, Sciter has special native behavior for WYSIWYG editing.

Please check sample: https://github.com/c-smile/sciter-js-sdk/tree/main/samples.sciter/editor-richtext
and documentation : https://github.com/c-smile/sciter-js-sdk/blob/main/docs/md/behaviors/behavior-richtext.md

These applications https://notes.sciter.com/ and https://html-notepad.com/ are both using that behavior.
