### ISSUE TITLE
import keyword doesn't work properly

### ISSUE THREAD

**Issue by AaronWright3** [c-smile/sciter-js-sdk#20]
Not sure if this is related to #12 , but `import * as sys from '@sys'` currently fails with the console error `SyntaxError: expecting '('`. The same goes for other importing modules, including individual variables/methods from those modules (sciter, env, etc.).

I can get import to work using the promise syntax, `const syspromise = import('@sys')`, and then finding the methods I need in the results of that promise, so it just seems to be an issue with import as a keyword.

**Comment by jsprog** [comment]
Please, try this without using a bundler like rollup
```js
<script type="module">
    // your import here
</script>
```

Note: I'll edit this after testing with rollup generated module (i.e: output.format: 'es')

**Comment by AaronWright3** [comment]
You're right, I was just mindlessly copying off of [the wiki page](https://github.com/c-smile/sciter-js-sdk/wiki/Module-sys) and forgot to make my script a module. Whoops!
