### ISSUE TITLE
What happened to the wiki?

### ISSUE THREAD

**Issue by abalter** [c-smile/sciter-js-sdk#203]
As of 10/15/2021, there does not seem to be a wiki for this project, despite the link in the [README](https://github.com/c-smile/sciter-js-sdk#see-sciterjs-wiki).

![image](https://user-images.githubusercontent.com/5349876/137576887-edbc32e5-3988-443b-9ced-7a6e6c6f05ab.png)

**Comment by c-smile** [comment]
I've removed Wiki for a while.
