### ISSUE TITLE
js userAgent load fail

### ISSUE THREAD

**Issue by azbo** [c-smile/sciter-js-sdk#22]
error:script: TypeError: cannot read property 'userAgent' of undefined
error:script:     at <anonymous> (this://app/js/vue.js:532)
    at <anonymous> (this://app/js/vue.js:8)
    at <eval> (this://app/js/vue.js:11964)

**Comment by c-smile** [comment]
That's one more subject for browser-compatibility.js (or whatever it will be named).

**Comment by c-smile** [comment]
Fixed in 4.4.5.9 by adding ```navigator``` native object
