### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by shithappens2016** [c-smile/sciter-js-sdk#229]
Drag the bottom right corner of the window and keep resizing the window significantly, you will find that the memory usage increases a lot, probably to about 200 megabytes, after which a little memory will be released, but there is still more than 100 megabytes of memory being occupied.

https://user-images.githubusercontent.com/13523412/144757610-870d1de4-d6a9-4879-a91d-3093af38ca7d.mp4

https://user-images.githubusercontent.com/13523412/144757620-560be226-1983-474a-804d-cf6403c0e812.mp4

https://user-images.githubusercontent.com/13523412/144757625-91c93a09-ae2a-4be9-9511-741824db59ad.mp4

https://user-images.githubusercontent.com/13523412/144757631-74b51333-4713-4bce-bcf4-3f7569603d25.mp4

```javascript
<html>
<head>
  <style>
    html { 
      background: transparent;
      overflow: none;
    }

    body {
      overflow: hidden;
      margin: 0;
      padding: 0;
    }
    
    #box_header {
      height: 40dip;
    }
    
    #box_toolbar {
      margin: 6dip 6dip 4dip 6dip;
      height: auto;
      color: rgba(255,255,255,.5);
    }
    
    #box_toolbar label {
      font-size: 13dip;
      margin-left: 10dip;
      display: inline-block;
    }
    
    #box_toolbar button {
      color: rgba(255,255,255,.5);
      font-size: 14dip;
    }
    
    #count {
      display: inline-block;
      width: *;
    }
    
    #box_main {
      margin: 6dip;
      border-spacing: 6dip; 
      flow:horizontal; 
      size: *;
      color: rgba(255,255,255,.5);
    }
    
    #box_main div {
      background: rgba(77, 77, 77, 0.3);
    }
    
    #box_src {
     vertical-align: middle;
     text-align: center;
     size: 1*;
    }
    
    #box_dst {
      size: 1*;
     vertical-align: middle;
     text-align: center;
    }
 
  </style>
</head>
<body>
<div #box_header></div>
<div #box_toolbar><button>test</button><label>test：</label><span #count>0</span><button #btn_work tabindex=1>test</button></div>
<div #box_main>
  <div #box_src></div>
  <div #box_dst></div>
</div>
</body>
</html>
```

**Comment by c-smile** [comment]
Cannot reproduce in actual Sciter (v. 4.4.8.18) on W10. 
After some number of cycles memory consumptions is stable:

![Memory consumption](https://sciter.com/wp-content/uploads/2021/12/memcons2.png)

DirectX/Direct2D and driver can do some caching, but I don't think this is the case on this screen.

Try on other machine to check is it is machine dependent.
