### ISSUE TITLE
Change 'window-frame' at runtime?

### ISSUE THREAD

**Issue by Heap-Hop** [c-smile/sciter-js-sdk#254]
In sciter-tis,we could change the window-frame at runtime like this:
`
self.timer(2s,function(){
    view.windowFrame = #solid;
})
`
It was a nice way to dynamically create/change different types of windows at runtime. 

But I can't find a way to do the same thing at sciter-js,
do me have the same method?
Thx!

**Comment by c-smile** [comment]
```JS
Window.this.frameType = "solid";
```

**Comment by Heap-Hop** [comment]
Thank you!
