### ISSUE TITLE
running scapp with parameter (path of html file) no longer work

### ISSUE THREAD

**Issue by MaherFa** [c-smile/sciter-js-sdk#263]
since 4.4.8.23
Windows 10 x64
scapp 32 and 64

when trying to start scapp with a path parameter : `scapp <path to main.htm>` it starts and shows the default window as if nothing was passed

**Comment by 8ctopus** [comment]
It's a bug that was introduced in 4.4.8.23, not present in 4.4.8.22-bis.
I believe @c-smile has [already fixed it](https://sciter.com/forums/topic/hello-world-tutorial-not-working-as-described/) in SVN.

**Comment by MaherFa** [comment]
true.. it is a recent bug , closing the issue since it is known and dealt with.. thx
