### ISSUE TITLE
Segmentation fault when using Element.Style.setProperty

### ISSUE THREAD

**Issue by thecodrr** [c-smile/sciter-js-sdk#267]
`el.style.setProperty("background", "blue");` causes a segmentation fault. Tried on 4.4.8.28.

**Comment by c-smile** [comment]
I do not see problems with this
```
<html>
    <head>
        <title>Test</title>
        <script>

document.body.style.setProperty("background", "blue"); 

        </script>
    </head>
    <body>
    </body>
</html>
```

**Comment by thecodrr** [comment]
I was trying out `solidjs` and it started crashing. Could be due to something else. Everything is working fine in React too.

**Comment by 8ctopus** [comment]
@thecodrr can be closed no?
