### ISSUE TITLE
Error: address already in use (related to named pipe)

### ISSUE THREAD

**Issue by jsprog** [c-smile/sciter-js-sdk#27]
**What we need?**
 A cross platform approach to clean resources related to named pipes.

**Some usecases for named pipes:**
* Forcing a single instance for app. Any other lauched instances should notify the first one and quit immediately (e.g: app.requestSingleInstanceLock() from electron)
* Named pipe "inspector-js" is used to establish communication between the inspector and apps (`sciter-sdk-js/demos/inspector/res/server.js`).

**The problems:**
* Failing to close listening to a named pipe (server) is preventing the next run for app to listen to it again. I already faced this with the inspector (this won't happen all the time) and I had to delete `/tmp/inspector-js` to avoid restarting my computer.
* The current implementation of the inspector is using a hard coded name for pipe. The problem isn't with this, but with allowing more useless instances to start.

**My recommendations for the inspector:** either, force a single instance, or allow other instances to start with different names for pipes.

**A work around for failures in closing a pipe:** don't start by binding a server to named pipe, but start by connecting as client:
* **Connected as client:**
  * Try to notify the other instance, then quit.
* **Failed to connect as client:**
  * Error: connection refused:
    * we need a cross platform approach to clean the resources related to pipe. In linux, we could achieve it with `rm /tmp/inspector-js`.
    * try to bind as server.
  * Error: no such file or directory:
    * try to bind as server.

**Comment by c-smile** [comment]
Fixed in 4.4.5.9 by checking if address is in use: https://github.com/c-smile/sciter-js-sdk/blob/main/demos/inspector/res/server.js#L106
