### ISSUE TITLE
how to make a http request,such as fetch

### ISSUE THREAD

**Issue by rydeanvi** [c-smile/sciter-js-sdk#3]
I am a web developer,I had use sciter for a longtime,I'm glad to see this project,and the quickjs did not provide http request api,will sciter.js provide fetch api such as chrome did？

**Comment by c-smile** [comment]
Yes, in next two weeks Sciter.JS will have core implementation of https://fetch.spec.whatwg.org/ API

**Comment by jsprog** [comment]
Nice news. Please consider adding support for WebSocket
[https://fetch.spec.whatwg.org/#websocket-protocol](url)


What can we gain from WebSocket?
- Realtime communication with servers
- Binary encoding (unlike sse)
- Live reload during development (e.g: rollup)
