### ISSUE TITLE
Window.this.modal bugged in v4.4.6.0

### ISSUE THREAD

**Issue by GirkovArpa** [c-smile/sciter-js-sdk#43]
Previous version of `x64/scapp.exe`, message box would close when you clicked "Ok".  Now, nothing happens, or the program crashes.

![preview](https://i.imgur.com/DGOoEfQ.gif)

**Comment by c-smile** [comment]
There is a bug on my side, yes.

**Comment by GirkovArpa** [comment]
Appears to be fixed with `v4.4.6.1`.
