### ISSUE TITLE
Question about python

### ISSUE THREAD

**Issue by martinlombana** [c-smile/sciter-js-sdk#53]
Hi!

If we want to run sciter-js inside python, like with https://github.com/sciter-sdk/pysciter, we should just exchange the dll and use the libsciter-gtk.so (in linux) or the dll for windows? Would that work out of the box?

Thanks!

**Comment by c-smile** [comment]
It should work OK as Sciter and Sciter.JS are ABI compatible. 
At least that's the intention so let me know if something will not work.

**Comment by martinlombana** [comment]
OK!. And, as for the raspberry pi, it would be the same? Or is there any thing else involved? I am receiving next week a rapberry pi 4, and I wanted to create a test with pysciter, sciter-js and pyinstaller (for packaging, portability).

**Comment by c-smile** [comment]
ARM32 version uses the same API as others.
