### ISSUE TITLE
(Question) about video streaming in sciter-js

### ISSUE THREAD

**Issue by martinlombana** [c-smile/sciter-js-sdk#60]
Is video rendering supported? I am trying to load in scapp.exe the simplest of the video-examples (with no TISSCRIPT) but it does not render the vídeo. Is there anything that must be done differently? ( Checked and the URL is ok and loads in a browser)

**test-video-streaming.htm**

Thanks in advance.

`<html>
    <head>
        <title>Test</title>
        <style>

          video {
            background: gray;
            size: *;
          }

        </style>
        <script type="text/tiscript"></script>
    </head>
    <body>

      Streaming from http://clips.vorwaerts-gmbh.de/VfE_html5.mp4 

      <video src="http://clips.vorwaerts-gmbh.de/VfE_html5.mp4" sizing=contain />
      

    </body>
</html>`

**Comment by MustafaHi** [comment]
It does work, try to install [K-Lite Codec Pack](https://codecguide.com/download_kl.htm)

**Comment by martinlombana** [comment]
There is no way to embed that codec, or use a codec that everyone usually
has? Or a way to embed the codec with the sources, so it does work in all
the installs of a sciter developed app?

I also tried with another normal mp4 file and it didn't work either. My
concern is to make it work in an ubiquitous way. Without external deps, or
with those deps, injected into the installation folder/code.

**Comment by martinlombana** [comment]
For myself & others:
https://sciter.com/forums/topic/embedding-videos-in-html-with-sciter/#post-58383
(I missed this before).

What is "weird", is that local videos are indeed reproduced without the
need for extra codecs (at least in windows). How does that work? Would it
behave the same way in a raspberry pi, locally?

Thanks,

**Comment by c-smile** [comment]
Sciter does not contain any video codecs but it allows to connect external sources of video frames for output.

I know several Sciter based projects are using ffmpeg to playback video in Sciter.

Here is demo of custom video frame source:
https://github.com/c-smile/sciter-sdk/blob/master/include/behaviors/behavior_video_generator_full.cpp

You can see it in action using wsciter.exe from Sciter SDK by loading this document in it : https://github.com/c-smile/sciter-sdk/blob/master/samples/video/video-generator-behavior-full-demo.htm

**Comment by martinlombana** [comment]
I see. I will digg into that because I would need ffmpeg to work on raspberry pi / windows. 

I see that with **sciter-js there is no wsciter.exe**, I see it in the regular sdk. What is exactly the difference between wsciter and scapp.exe? And usciter?

And why that example only works with wsciter.exe? 

I tried looking for info in the website/docs, but couldn't find it. Thanks.
