### ISSUE TITLE
Behavior:virtual-list bugs?

### ISSUE THREAD

**Issue by 000o0** [c-smile/sciter-js-sdk#65]
## # 1
When adding a new item to the virtual-list and scrolling down(using `vlist.lastElementChild.scrollIntoView()`) immediately, 
the item is added at an incorrect location.

<a href="https://gifyu.com/image/YnAI"><img src="https://s4.gifyu.com/images/149645a805324eae0.gif" alt="149645a805324eae0.gif" border="0" /></a>

## # 2
When changes (delete/replace) occur in virtual-list items, scroll bars are not rendered correctly.

<a href="https://gifyu.com/image/YnA6"><img src="https://s4.gifyu.com/images/2f9595f994b4c0f1a.gif" alt="2f9595f994b4c0f1a.gif" border="0" /></a>

## # 3
Certain virtual-list item is rendered multiple times intermittently. (see `Test Message 500`)

<a href="https://gifyu.com/image/YnAR"><img src="https://s4.gifyu.com/images/3c895a3cde22b838d.gif" alt="3c895a3cde22b838d.gif" border="0" /></a>

##
Sample project used for the above test is here.
[vlist-test-sample.zip](https://github.com/c-smile/sciter-js-sdk/files/6248483/vlist-test-sample.zip)

**Comment by c-smile** [comment]
These are not the behavior bugs but rather is misunderstanding of how that behavior works.

Here: 
https://github.com/c-smile/sciter-js-sdk/commit/21ff5f8e46d721713780f6411691298065dcb9f9

I've added documentation and updated the sample. 

Note use of record indexes as keys works only in case of non-modifiable lists. 
But in your case record keys shall be permanent - record once appeared on the list shall not change the key. And that is where your code fails.
