### ISSUE TITLE
Modals w/ 'url' param not working on macOS

### ISSUE THREAD

**Issue by AlecHaring** [c-smile/sciter-js-sdk#67]
If a modal is initialized with the 'url' param set, nothing will pop up but the main window will freeze up as though one is showing. It's almost as if the modal is invisible. This behavior can be recreated inside of uSciter using the 'msgbox+dialog' sample.

https://user-images.githubusercontent.com/19616756/113805951-752be480-972f-11eb-85e7-b070bdd5d70d.mov

**Comment by c-smile** [comment]
Thanks, fixed by this: https://github.com/c-smile/sciter-js-sdk/commit/402ee3946ff8c632904ecbb20ac9fcf22f70d51f
