### ISSUE TITLE
no source code

### ISSUE THREAD

**Issue by Ksengine** [c-smile/sciter-js-sdk#7]
include source code instead of binaries
include binaries in releases

**Comment by c-smile** [comment]
I've [tried to gather funds](https://www.kickstarter.com/projects/c-smile/open-source-sciter-engine) for opening source of the Sciter but no luck - not too much interest for that so far.

So Sciter development is happening in closed source mode for a while - that's significantly less expensive for me.

**Comment by Ksengine** [comment]
i can understand

**Comment by Ksengine** [comment]
but we(developers) help open source projects.
sciter cant render webpages correctly(like web browsers)
it has some errors when rendering google.com
so sciter eeds to be developed

**Comment by c-smile** [comment]
> sciter cant render webpages correctly

And it should not - Sciter is not a browser. Don't expect it to render "properly" any random page taken Wild Wild Web.
It is a UI engine.  If to choose  between correct rendering and compact code I, as an author, will chose compact code - I don't want to create another Electron.

**Comment by Ksengine** [comment]
> I've tried to gather funds for opening source of the Sciter but no luck - not too much interest for that so far.

many popular apps used sciter
they should help you
include your sponsor button in github and sciter.com

**Comment by Ksengine** [comment]
if this repo is open source, without creating another electron we can create good renderer.
thats all

**Comment by GirkovArpa** [comment]
@Ksengine You are not taking into account all the previous work and research about the business side of this project which the author (as well as others) have performed regarding this project over the last decade and a half.
