### ISSUE TITLE
behavior `htmlarea` not working after 4.4.6.4

### ISSUE THREAD

**Issue by wdcossey** [c-smile/sciter-js-sdk#72]
Seems that the `htmlarea` behavior is no longer working after updating to Sciter.JS v4.4.6.4.

Tested version(s):
* 4.4.6.4
* 4.4.6.5
* 4.4.6.6

Tested platform(s):
* Windows

Basic Example:
```css
div
{
    behavior: htmlarea;
}
```

```html
<div><span>Hello:</span>&nbsp;<span style="font-weight: bold;">Sciter</span></div>
```

Expected behaviour is that the text/content within the div can be selected with the mouse.

**Comment by c-smile** [comment]
My pardon, forgot to mention it.

Use `behavior: selectable;`  that is new name of what was known as `behavior:htmlarea;`

**Comment by wdcossey** [comment]
@c-smile Thanks, you can close this issue.
I did check the logfile before raising the issue, I didn't see see anything mentioned and thought it was a bug.

Are `Sciter` and `SciterJS` going to have diverging paths in future as Sciter >= 4.4.6.4 still uses `htmlarea`.

**Comment by DhruvaSambrani** [comment]
Also, mathjax doesn't seem to work, with an error "Mathjax(?): not a function". Is this expected? How do I work around this?
