### ISSUE TITLE
Undocumented: Window.this.screenBox('snapshot')

### ISSUE THREAD

**Issue by GirkovArpa** [c-smile/sciter-js-sdk#75]
```javascript
Window.this.screenBox('snapshot'); // returns an Image of the entire screen
```

I use it [here](https://github.com/GirkovArpa/screenshot-delta-detector/blob/1eeae874efa2e6f6a9ad6edc38e1d001be6c8b08/main.js#L33) to take a screenshot of the entire screen, but I only knew about it from [previous experience](https://github.com/GirkovArpa/red-pixel-screenshotter/blob/4928d6aeb90780ed1112b8ddb449d3f028476373/script.tis#L28) with Sciter.TIS.  

Maybe others would find it helpful to know that screenshot-capability exists.

**Comment by c-smile** [comment]
Fixed, thanks
