### ISSUE TITLE
Outline doesn't work on absolutely positioned input

### ISSUE THREAD

**Issue by GirkovArpa** [c-smile/sciter-js-sdk#76]
Minimal reproducible example:

```html
<input style="outline: 1px solid red; position: absolute;">
```

The outline works if `position: absolute;` is removed.

Buttons don't have this problem:

```html
<button style="outline: 1px solid red; position: absolute"></button>
```

I need to absolutely position elements for a form editor:

![screenshot](https://i.imgur.com/wNFnKpa.gif)

**Comment by c-smile** [comment]
Fixed in 4.4.7.0
