### ISSUE TITLE
Html item gets repeated in inspector an arbitrary number of times

### ISSUE THREAD

**Issue by martinlombana** [c-smile/sciter-js-sdk#80]
![image](https://user-images.githubusercontent.com/18351919/115274290-c92bc580-a140-11eb-93d1-6626b899403f.png)

Using latest version from github.

Using usciter.exe, even with a simple example like:

```
<html lang="en" window-resizable="true" window-wclassth="400dip" window-height="600dip" theme="light">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="wclassth=device-wclassth, initial-scale=1.0">
    <title>Test</title>
</head>

<body>
</body>

</html>

```

**Comment by c-smile** [comment]
Cannot reproduce this, not in scapp.exe nor in usciter.exe
