### ISSUE TITLE
Possible issue with alignment: Text-align center

### ISSUE THREAD

**Issue by martinlombana** [c-smile/sciter-js-sdk#82]
Unles I am missing somethign (probably yes), I am encountering a slight problem that is weird. When using text-align center, all objects are centered as expected (image in this case), but when the bounding box is made smaller, the image does not keep the centered alignment. There is overflow: hidden and that is what I want. But I want the image to remain centered, even though I'll be lossing parts of it on the sides. 
When I align that image to the right, it works as expected, and it is anchored to the right, same to the left. 

![center](https://user-images.githubusercontent.com/18351919/115433817-4110f300-a208-11eb-9a83-5af89bf162cc.gif)

The end result that I am looking for when resizing is this:

![image](https://user-images.githubusercontent.com/18351919/115434133-a06f0300-a208-11eb-87f1-5198bd51a15c.png)

but I get this:

![image](https://user-images.githubusercontent.com/18351919/115434161-acf35b80-a208-11eb-9371-b608c961f9e4.png)

```html
<!DOCTYPE html>
<html lang="en"
   window-resizable="true"
   window-frame="extended"
   window-icon="extra/calculator.svg"
   window-width="400dip"
   window-height="600dip"
   theme="light">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Test</title>
  <style>

body {
  padding: 0;
  margin: 0;
}

.inner{
	background-color: red;
	color: white;
	vertical-align:middle;
	size: *;
	margin: 10px;
	overflow: hidden;
	text-align: center;
}

.calculator-grid > button {
  cursor: pointer;
  font-size: 2rem;
  border: 1px solid black;
  outline: none;
  background-color: rgba(255, 255, 255, .75);
}

.calculator-grid > button:hover {
  background-color: rgba(255, 255, 255, .9);
}

  html {
    background: transparent; // we use blurbehind
    overflow: none;          // sciter specific - no owerflow
  }

  .calculator-grid {
    flow: grid( 1  1  1  1,
                2  2  3  4,
                5  6  7  8,
                9  10 11 12,
                13 14 15 16,
                17 18 19 19 ); // the layout
    size:*;  // spans whole space
	border-spacing: 10px;
  }

  button {
    style-set: none; // no standard decoration
    behavior:button;
    display: block;
    size:*;  // flexible - fills grid cell
    vertical-align:middle;
    text-align:center;
	overflow: hidden;



  }
h1{
    margin:0;
}
img {
margin: 0;
max-width: 140px;

}
  .output {
    flow: vertical;
    size:*;  // flexible - fills grid cell
    text-align: right;
    vertical-align:bottom;
  }


  </style>
</head>

<body>
  <div class="calculator-grid">
    <div class="output">
		TOP CONTENT
    </div>
    <button data-all-clear class="span-two">0</button>
    <button data-delete>1</button>
    <button data-operation>2</button>
    <button data-number>3</button>
    <button data-number><div class="inner"><h1>4</h1></div></button>
    <button data-number><div class="inner"><img src="test.png"/></div></button>
    <button data-operation>6</button>
    <button data-number>7</button>
    <button data-number>8</button>
    <button data-number>9</button>
    <button data-operation>10</button>
    <button data-number>1</button>
    <button data-number>12</button>
    <button data-number>13</button>
    <button data-operation>14</button>
    <button data-number>15</button>
    <button data-number>16</button>
    <button data-equals>17</button>
  </div>
</body>
</html>

```

**Comment by c-smile** [comment]
> Unles I am missing somethign (probably yes)

Why "probably" ?

Try this: 

```html
<html>
    <head>
        <title>Test</title>
        <style>

img { 
  size:300px;
  margin-left:50%;
  transform: translate(-50%,0);
}

button {
  display:block;
  width:*;
  min-width:0;
  overflow:hidden;
  height:300px;
  padding:0;
}

        </style>
    </head>
    <body>
       <button><img src="tref.png"/></button>
    </body>
</html>
```

See: https://www.w3.org/Style/Examples/007/center.en.html

**Comment by martinlombana** [comment]
Interesting. I have, for a longtime, used text-transform: translate to center things. But I stoped using it long time ago because it would made contents blurry randomly (specially in chrome), due to lack of rounding of pixel values and things looked off, and "cheap". In sciter this is not a problem?

**Comment by martinlombana** [comment]
As a note, I usually did it with Flex alignment:

` 
display: flex;
 justify-content: center;
 align-items: center;
`

**Comment by c-smile** [comment]
> In sciter this is not a problem?

For text that's also a problem as transform usually prevents ClearType text.

In Sciter we use `horizontal-align:center;` for that purpose:  

```html
<html>
    <head>
        <title>Test</title>
        <style>

img { 
  size:300px;
}

button {
  display:block;
  flow:horizontal;  horizontal-align:center;  
  width:*;
  min-width:0;
  overflow:hidden;
  height:300px;
  padding:0;
}

        </style>
    </head>
    <body>
       <button><img src="tref.png"/></button>
    </body>
</html>
```

**Comment by martinlombana** [comment]
Before asking here I looked for something similar to "horizontal-align" here:

https://sciter.com/docs/content/css/cssmap.html

But **horizontal-align** seems not to be listed. 

Is there any other sciter-css reference besides that link?

**Comment by c-smile** [comment]
> Is there any other sciter-css reference besides that link?

It is coming
