### ISSUE TITLE
Sciter-js-sdk not working with pySciter

### ISSUE THREAD

**Issue by rjcreluda** [c-smile/sciter-js-sdk#85]
I tried to run Sciter.js with pysciter, I just exchange the dll from sciter-js-sdk.
When I execute it, the following error occur:

Traceback (most recent call last):
  File "E:\ice2\BD mr Nicolas\sciter-js\test-sciter-js.py", line 16, in <module>
    frame = sciter.Window()
  File "C:\Users\Jind\AppData\Local\Programs\Python\Python37\lib\site-packages\sciter\window.py", line 35, in __init__
    self.setup_debug()
  File "C:\Users\Jind\AppData\Local\Programs\Python\Python37\lib\site-packages\sciter\host.py", line 47, in setup_debug
    _api.SciterSetupDebugOutput(hwnd, None, self._sciter_debug_proc)
OSError: exception: access violation writing 0x0000000000000000

This line causes the error: 
frame = sciter.Window(ismain=True, uni_theme=True)

**Comment by jsprog** [comment]
Not an issue but a breaking change for other wrappers starting from version [4.4.7.0](https://github.com/c-smile/sciter-js-sdk/blob/main/logfile.md#4470).

**Comment by rjcreluda** [comment]
> 
> 
> Not an issue but a breaking change for other wrappers starting from version [4.4.7.0](https://github.com/c-smile/sciter-js-sdk/blob/main/logfile.md#4470).

Thank you. How can I make it works again, is there a way?

**Comment by c-smile** [comment]
https://github.com/sciter-sdk/pysciter/issues/41

**Comment by rjcreluda** [comment]
Solved! I remove pysciter package installed from pip. Then I download and install [pysciter](https://github.com/sciter-sdk/pysciter) with Sciter API Unification fixed.

**Comment by pravic** [comment]
I've updated pysciter on pip as well.
