### ISSUE TITLE
Bin for windows x64 get crash

### ISSUE THREAD

**Issue by lynnux** [c-smile/sciter-js-sdk#86]
4.4.7.2 get crash, but 4.4.6.8 is OK, I debuged, find out that:
in 4.4.7.2, the rust app call `_API.SciterCreateWindow`, which is NULL, so the latest ISciterAPI changed?

**Comment by c-smile** [comment]
https://github.com/sciter-sdk/rust-sciter/issues/107

**Comment by pravic** [comment]
@lynnux Sciter SDK version is 4.4.7.2.

Is it Sciter.JS or Sciter.TIS? 
Is it Sciter.Lite?

**Comment by lynnux** [comment]
@pravic I download sciter.dll from https://github.com/c-smile/sciter-js-sdk/blob/main/bin/windows/x64/sciter.dll, and `sciter-rs = "0.5.55"`, It's OK after set `sciter-rs = {git="https://github.com/sciter-sdk/rust-sciter.git"}`, so your commit are not plublish yet, I should close this issue

**Comment by pravic** [comment]
Oh, right. Thanks.

**Comment by pravic** [comment]
Published a release as well.
