### ISSUE TITLE
In JavaScript, typeof native function will return "string"

### ISSUE THREAD

**Issue by lk9015** [c-smile/sciter-js-sdk#93]
ValueNativeFunctorSet doesn't work in Sciter.JS. In JavaScript, typeof native function will return "string"

**Comment by c-smile** [comment]
Will be available in the next build.

**Comment by c-smile** [comment]
Implemented in 4.4.7.4 and demonstrated in the _integration_ project: https://github.com/c-smile/sciter-js-sdk/blob/main/demos/integration/frame.cpp#L90

**Comment by lk9015** [comment]
It works fine, thanks.
